typography_spectrum: 0.07082471321336925
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.03857292630709708
  lightness: 0.23754866747185588
  saturation: 0.7408643465023488
  rhythmicContrast: 0.7708855585660785
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.819152322364971
analytics:
  google: null
  facebook: null
  twitter: null
name: in sync music production
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Studio H2O
description: show me the music!
purpose: []
